language: go

go:
  - 1.10

env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - go get github.com/tools/godep
  - godep restore
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr
after_success:
  - test "$TRAVIS_TAG" != "" && gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}" -ldflags "-X main.Version=$TRAVIS_TAG"
  - test "$TRAVIS_TAG" != "" && ghr --username VDMi --repository TrelloToJira --token $GITHUB_TOKEN -c $TRAVIS_COMMIT --replace --debug "$TRAVIS_TAG" dist/
